language: java
before_install:
- cd libs && ./install.sh && cd ..
after_success:
- ./createLibrary.sh
deploy:
  provider: releases
  api_key:
    secure: Ms4BzxnnB668WGGjMVY/wYQtNcvBryEqL9VTilFvuvzqe084doh8WMJqs09e0ygexWjeC5GwKEBH8xqifMX3yEz5GZnusCVCM1zchmL2dwUKHQ0r2Ih/DZ7ml/5nqiqQP80wGNfj1o032a5rDhfLt91U5X05DdC3MKqvEq3mz6E=
  file: LSLLink.tgz
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
